### ISSUE TITLE
When deleting (removing) an area in Hoshin the dialog doesn't close and the screen doesn't refresh

### ISSUE THREAD

**Issue by Germanicus1** [gabriprat/hoshinplan#111]
Steps to reproduce:

1. Create a new area in a Hoshin
2. Click on the area's name
3. Click on 'Remove'

**Result:** No feedback and the dialog stays open
**Expected result:** dialog is closed and the area has disappeared (maybe with a warning that objectives and indicators will be deleted)
**Work-a-round:** Close the dialog and reload the page manually (works but is ugly)

**Comment by gabriprat** [comment]
Fixed! Thank you for finding that one.
