### ISSUE TITLE
Error al iniciar session

### ISSUE THREAD

**Issue by alberique** [gabriprat/hoshinplan#113]
![image](https://cloud.githubusercontent.com/assets/10523603/7024982/c2207a1c-dd40-11e4-82b3-fbbf3e598c74.png)

**Comment by alberique** [comment]
Me ha mandado Toni una invitación a la cuenta corporativa y no me llega el email.
Despues al intentar hacer login directamente, me lleva a la página de Schibsted pero me da el error adjuntado anteriormente.

**Comment by gabriprat** [comment]
Arreglado! Se me había olvidado cerrar el ticket. :)
