### ISSUE TITLE
Errors when updating two Hoshin KPIs 

### ISSUE THREAD

**Issue by Annaquin** [gabriprat/hoshinplan#117]
Hi!

Our user sandra [at] az.com is trying to update the following KPIs through the /history page and "Editar tabla de valores" feature and the system shows a red message error stating that it's not possible and we should try later. We have done so, but no success, so far.

https://www.hoshinplan.com/indicators/1346-weekly-sales-adsense/history

https://www.hoshinplan.com/indicators/1249-weekly-sales-devs-overall/history

Thanks for solving this. :)

**Comment by gabriprat** [comment]
Fixed! It was an error that prevented very long requests to reach the server. Thank you for spotting it and sorry about me taking too long to fix it.
