### ISSUE TITLE
Invalid Dockerfile

### ISSUE THREAD

**Issue by jcaromiq** [gabriprat/hoshinplan#127]
Hi,
I have a fork with a updated and valid Dockerfile, if you think it would be ok, I can do a pullRequest

Thank you

**Comment by gabriprat** [comment]
Hi,

Thank you for your proposal. 

The space you removed is supposed to be there to clone the repo to /opt

Do you have problems with the Dockerfile? We are using it to build and run the application as is. 

Best, 
Gabri
