### ISSUE TITLE
Creating a task produces error message

### ISSUE THREAD

**Issue by Germanicus1** [gabriprat/hoshinplan#132]
When clicking on submit while creating a task creates an error and the task is not created.

![image](https://cloud.githubusercontent.com/assets/1483411/25795756/0f104688-33d7-11e7-88a3-cb03e9445fcd.png)

I tried both creating a task by clicking on the task icon by the objective and clicking on "New Task". Same result.

**Comment by Germanicus1** [comment]
The problem solved itself!? :)

**Comment by Germanicus1** [comment]
The error still exists. Setting the deadline seems to cause the error.

**Comment by gabriprat** [comment]
I changed some js and css libraries. Probably a bad idea or bad executed. 

Should be fixed now.
